const ROLES = Object.freeze({
  CITIZEN: 'CITIZEN',
  SACHIVALAYAM_STAFF: 'SACHIVALAYAM_STAFF',
  MANDAL_OFFICER: 'MANDAL_OFFICER',
  DISTRICT_OFFICER: 'DISTRICT_OFFICER',
  ADMIN: 'ADMIN'
});

const ALL_ROLES = Object.values(ROLES);
const STAFF_LIKE_ROLES = [ROLES.SACHIVALAYAM_STAFF, ROLES.MANDAL_OFFICER, ROLES.DISTRICT_OFFICER];
const OFFICER_ROLES = [ROLES.MANDAL_OFFICER, ROLES.DISTRICT_OFFICER];
const STAFF_PROVISIONED_ROLES = [...STAFF_LIKE_ROLES, ROLES.ADMIN];

const COMPLAINT_STATUS = Object.freeze({
  REGISTERED: 'REGISTERED',
  ASSIGNED: 'ASSIGNED',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  ACTION_TAKEN: 'ACTION_TAKEN',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REOPENED: 'REOPENED'
});

const OPEN_STATUSES = [
  COMPLAINT_STATUS.REGISTERED,
  COMPLAINT_STATUS.ASSIGNED,
  COMPLAINT_STATUS.UNDER_INVESTIGATION,
  COMPLAINT_STATUS.ACTION_TAKEN,
  COMPLAINT_STATUS.REOPENED
];

const TERMINAL_STATUSES = [COMPLAINT_STATUS.RESOLVED, COMPLAINT_STATUS.CLOSED];

// Valid forward transitions for the complaint lifecycle finite state machine.
// REOPENED behaves like ASSIGNED re-entry (goes back into the active workflow).
const VALID_TRANSITIONS = Object.freeze({
  [COMPLAINT_STATUS.REGISTERED]: [COMPLAINT_STATUS.ASSIGNED],
  [COMPLAINT_STATUS.ASSIGNED]: [COMPLAINT_STATUS.UNDER_INVESTIGATION],
  [COMPLAINT_STATUS.UNDER_INVESTIGATION]: [COMPLAINT_STATUS.ACTION_TAKEN],
  [COMPLAINT_STATUS.ACTION_TAKEN]: [COMPLAINT_STATUS.RESOLVED],
  [COMPLAINT_STATUS.RESOLVED]: [COMPLAINT_STATUS.CLOSED, COMPLAINT_STATUS.REOPENED],
  [COMPLAINT_STATUS.CLOSED]: [COMPLAINT_STATUS.REOPENED],
  [COMPLAINT_STATUS.REOPENED]: [COMPLAINT_STATUS.UNDER_INVESTIGATION]
});

const SENSITIVE_CATEGORY_CODES = Object.freeze([
  'CORRUPTION',
  'BRIBERY',
  'STAFF_MISCONDUCT',
  'ABUSE_OF_POWER',
  'NEGLIGENCE'
]);

const CATEGORY_CODES = Object.freeze([
  'MUNICIPAL_SERVICES',
  'WATER_SUPPLY',
  'DRAINAGE',
  'ROADS',
  'STREET_LIGHTS',
  'SANITATION',
  'HEALTH_SERVICES',
  'EDUCATION',
  'REVENUE_DEPARTMENT',
  'CERTIFICATES',
  'PENSION_SERVICES',
  'WELFARE_SCHEMES',
  'AGRICULTURE',
  'HOUSING',
  'ELECTRICITY',
  'PUBLIC_DISTRIBUTION_SYSTEM',
  'WOMEN_CHILD_WELFARE',
  'EMPLOYMENT',
  'ENVIRONMENT',
  'CORRUPTION',
  'BRIBERY',
  'STAFF_MISCONDUCT',
  'ABUSE_OF_POWER',
  'NEGLIGENCE',
  'OTHER'
]);

const FILE_TYPE = Object.freeze({
  IMAGE: 'IMAGE',
  DOCUMENT: 'DOCUMENT',
  VIDEO: 'VIDEO'
});

const ALLOWED_MIME_TYPES = Object.freeze({
  [FILE_TYPE.IMAGE]: ['image/jpeg', 'image/png', 'image/jpg'],
  [FILE_TYPE.DOCUMENT]: [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ],
  [FILE_TYPE.VIDEO]: ['video/mp4']
});

const ESCALATION_LEVEL = Object.freeze({
  ASSIGNMENT_BREACH: 'ASSIGNMENT_BREACH',
  MANDAL_LEVEL_1: 'MANDAL_LEVEL_1',
  DISTRICT_LEVEL_2: 'DISTRICT_LEVEL_2'
});

const ESCALATION_TRIGGER = Object.freeze({
  SYSTEM: 'SYSTEM',
  MANUAL: 'MANUAL'
});

const NOTIFICATION_TYPE = Object.freeze({
  STATUS_CHANGE: 'STATUS_CHANGE',
  ASSIGNMENT: 'ASSIGNMENT',
  ESCALATION: 'ESCALATION',
  FEEDBACK_REQUEST: 'FEEDBACK_REQUEST',
  REOPEN: 'REOPEN',
  SYSTEM: 'SYSTEM'
});

const NOTIFICATION_CHANNEL = Object.freeze({
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  WHATSAPP: 'WHATSAPP'
});

const DELIVERY_STATUS = Object.freeze({
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  FAILED: 'FAILED',
  DELIVERED: 'DELIVERED'
});

const SUPPORTED_LANGUAGES = Object.freeze(['te', 'en', 'hi']);
const DEFAULT_LANGUAGE = 'en';

const GEO_LEVELS = Object.freeze(['district', 'mandal', 'village', 'sachivalayam']);

const OTP_PURPOSE = Object.freeze({
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN'
});

module.exports = {
  ROLES,
  ALL_ROLES,
  STAFF_LIKE_ROLES,
  OFFICER_ROLES,
  STAFF_PROVISIONED_ROLES,
  COMPLAINT_STATUS,
  OPEN_STATUSES,
  TERMINAL_STATUSES,
  VALID_TRANSITIONS,
  SENSITIVE_CATEGORY_CODES,
  CATEGORY_CODES,
  FILE_TYPE,
  ALLOWED_MIME_TYPES,
  ESCALATION_LEVEL,
  ESCALATION_TRIGGER,
  NOTIFICATION_TYPE,
  NOTIFICATION_CHANNEL,
  DELIVERY_STATUS,
  SUPPORTED_LANGUAGES,
  DEFAULT_LANGUAGE,
  GEO_LEVELS,
  OTP_PURPOSE
};
