export const ROLES = {
  CITIZEN: 'CITIZEN',
  SACHIVALAYAM_STAFF: 'SACHIVALAYAM_STAFF',
  MANDAL_OFFICER: 'MANDAL_OFFICER',
  DISTRICT_OFFICER: 'DISTRICT_OFFICER',
  ADMIN: 'ADMIN'
};

export const STAFF_LIKE_ROLES = [ROLES.SACHIVALAYAM_STAFF, ROLES.MANDAL_OFFICER, ROLES.DISTRICT_OFFICER];
export const OFFICER_ROLES = [ROLES.MANDAL_OFFICER, ROLES.DISTRICT_OFFICER];

export const COMPLAINT_STATUS = {
  REGISTERED: 'REGISTERED',
  ASSIGNED: 'ASSIGNED',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  ACTION_TAKEN: 'ACTION_TAKEN',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REOPENED: 'REOPENED'
};

export const STATUS_ORDER = [
  COMPLAINT_STATUS.REGISTERED,
  COMPLAINT_STATUS.ASSIGNED,
  COMPLAINT_STATUS.UNDER_INVESTIGATION,
  COMPLAINT_STATUS.ACTION_TAKEN,
  COMPLAINT_STATUS.RESOLVED,
  COMPLAINT_STATUS.CLOSED
];

export const OPEN_STATUSES = [
  COMPLAINT_STATUS.REGISTERED,
  COMPLAINT_STATUS.ASSIGNED,
  COMPLAINT_STATUS.UNDER_INVESTIGATION,
  COMPLAINT_STATUS.ACTION_TAKEN,
  COMPLAINT_STATUS.REOPENED
];

// Valid forward transitions, mirroring the backend FSM - used to build the
// "update status" dropdown so staff/officers never see an invalid option.
export const VALID_TRANSITIONS = {
  [COMPLAINT_STATUS.REGISTERED]: [COMPLAINT_STATUS.ASSIGNED],
  [COMPLAINT_STATUS.ASSIGNED]: [COMPLAINT_STATUS.UNDER_INVESTIGATION],
  [COMPLAINT_STATUS.UNDER_INVESTIGATION]: [COMPLAINT_STATUS.ACTION_TAKEN],
  [COMPLAINT_STATUS.ACTION_TAKEN]: [COMPLAINT_STATUS.RESOLVED],
  [COMPLAINT_STATUS.RESOLVED]: [COMPLAINT_STATUS.CLOSED],
  [COMPLAINT_STATUS.CLOSED]: [],
  [COMPLAINT_STATUS.REOPENED]: [COMPLAINT_STATUS.UNDER_INVESTIGATION]
};

export const CATEGORY_CODES = [
  'MUNICIPAL_SERVICES', 'WATER_SUPPLY', 'DRAINAGE', 'ROADS', 'STREET_LIGHTS',
  'SANITATION', 'HEALTH_SERVICES', 'EDUCATION', 'REVENUE_DEPARTMENT', 'CERTIFICATES',
  'PENSION_SERVICES', 'WELFARE_SCHEMES', 'AGRICULTURE', 'HOUSING', 'ELECTRICITY',
  'PUBLIC_DISTRIBUTION_SYSTEM', 'WOMEN_CHILD_WELFARE', 'EMPLOYMENT', 'ENVIRONMENT',
  'CORRUPTION', 'BRIBERY', 'STAFF_MISCONDUCT', 'ABUSE_OF_POWER', 'NEGLIGENCE', 'OTHER'
];

export const SENSITIVE_CATEGORY_CODES = ['CORRUPTION', 'BRIBERY', 'STAFF_MISCONDUCT', 'ABUSE_OF_POWER', 'NEGLIGENCE'];

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'hi', label: 'हिन्दी' }
];

export const FILE_LIMITS = {
  IMAGE: { maxBytes: 10 * 1024 * 1024, types: ['image/jpeg', 'image/png', 'image/jpg'] },
  DOCUMENT: {
    maxBytes: 20 * 1024 * 1024,
    types: ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
  },
  VIDEO: { maxBytes: 50 * 1024 * 1024, types: ['video/mp4'] }
};

export const STATUS_COLOR = {
  [COMPLAINT_STATUS.REGISTERED]: 'bg-sand-light text-ink',
  [COMPLAINT_STATUS.ASSIGNED]: 'bg-teal-100 text-teal-700',
  [COMPLAINT_STATUS.UNDER_INVESTIGATION]: 'bg-teal-100 text-teal-700',
  [COMPLAINT_STATUS.ACTION_TAKEN]: 'bg-teal-100 text-teal-700',
  [COMPLAINT_STATUS.RESOLVED]: 'bg-moss-50 text-moss-600',
  [COMPLAINT_STATUS.CLOSED]: 'bg-moss-50 text-moss-600',
  [COMPLAINT_STATUS.REOPENED]: 'bg-rust-50 text-rust-600'
};
